### PR TITLE
Fix #1000: unwrap response envelope in thermal battery forecast parsing

### LINKED ISSUE #1000: Bug: Thermal battery forecast parsing fails — WS response has 'response' wrapper
## Summary

The thermal battery **never** uses weather forecast data for its skip/direction logic. It always falls back to the current outdoor temp sensor, which uses the wide ±20°F skip zone against a single point-in-time reading instead of the smarter forecast-based logic.

## Root Cause

`tryFetchForecast()` in `thermal_battery.go` parses the `result` from `CallServiceWithResponse()` as if the entity data is at the top level:

```go
var parsed map[string]struct {
    Forecast []forecastEntry `json:"forecast"`
}
if err := json.Unmarshal(result, &parsed); err != nil { ... }

entityData, ok := parsed[entity]   // ← always false
```

But the **actual** HA WebSocket API `result` for `call_service` with `return_response: true` wraps the data in a `response` key:

```json
{
  "context": { "id": "...", "parent_id": null, "user_id": "..." },
  "response": {
    "weather.strawberry_creek": {
      "forecast": [
        { "temperature": 72, "templow": 37, ... }
      ]
    }
  }
}
```

The Go code unmarshals this into `map[string]struct{...}` which silently succeeds (Go ignores unknown keys like `context` and `response`), but `parsed["weather.strawberry_creek"]` is never found because the entity key is nested one level deeper under `response`.

The result: `tryFetchForecast` always logs `"No forecast entries found in response"`, the negative cache kicks in, and the system falls back to the outdoor temp sensor every time.

## Why Tests Pass

The mock client (`MockClient.SetServiceResponse`) injects the response **without** the `response` wrapper:

```go
// thermal_battery_test.go
func makeForecastResponse(high, low float64) json.RawMessage {
    resp := fmt.Sprintf(`{"%s":{"forecast":[{"temperature":%v,"templow":%v}]}}`, ...)
    return json.RawMessage(resp)
}
```

So tests never exercise the real response structure.

## Verified via Live WebSocket

Confirmed by connecting directly to the HA WebSocket API:

```
=== RESULT TOP-LEVEL KEYS: [ "context", "response" ]
=== RESULT.RESPONSE KEYS: [ "weather.strawberry_creek" ]
```

Both forecast sources (`weather.strawberry_creek` and `weather.forecast_home_2`) return valid forecast data — the data is there, it just can not be found due to the missing unwrap.

## Impact

- Thermal battery always uses current outdoor temp fallback instead of daily forecast high/low
- On a day like today (outdoor temp 51°F, forecast high 72°F / low 37°F), the fallback logic sees 51°F as "within skip zone (49-94°F)" and skips activation
- The forecast logic would correctly see the high of 72°F still within skip zone but low of 37°F below 49°F → would activate pre-heating
- This means the thermal battery has **never** activated using forecast logic since the feature was implemented

### Option A: Unwrap in `tryFetchForecast` (minimal change)

```go
// Add a wrapper struct to handle the HA WebSocket response format
type serviceResponseWrapper struct {
    Response json.RawMessage `json:"response"`
}

func (m *Manager) tryFetchForecast(entity string) (float64, float64, bool) {
    result, err := m.haClient.CallServiceWithResponse(...)
    // ... existing nil/error checks ...

    // Unwrap the "response" envelope from the WS result
    var wrapper serviceResponseWrapper
    if err := json.Unmarshal(result, &wrapper); err != nil || wrapper.Response == nil {
        // Fall back to parsing result directly (forward-compat)
        wrapper.Response = result
    }

    var parsed map[string]struct {
        Forecast []forecastEntry `json:"forecast"`
    }
    if err := json.Unmarshal(wrapper.Response, &parsed); err != nil {
        ...
    }
    // ... rest unchanged
}
```

### Option B: Unwrap in `CallServiceWithResponse` (fixes it for all callers)

Extract the `response` field from `result` in the HA client itself, so all callers get the clean entity-level data. This would match what the mock already returns.

### Fix the mock too

Either way, `makeForecastResponse` in the test should be updated to wrap the response realistically:

```go
func makeForecastResponse(high, low float64) json.RawMessage {
    resp := fmt.Sprintf(`{"context":{"id":"test"},"response":{"%s":{"forecast":[{"temperature":%v,"templow":%v}]}}}`,
        forecastWeatherEntityPrimary, high, low)
    return json.RawMessage(resp)
}
```

## Environment

- HA version: 2026.3.1
- Go service communicates via WebSocket API
- Both `weather.strawberry_creek` (WeatherFlow Tempest) and `weather.forecast_home_2` (Met.no) are working and return valid forecasts

### PR DESCRIPTION
**Pull request by NickBorgers**
Resolves #1000

## Summary

The HA WebSocket API wraps `call_service` results (with `return_response:true`) in a `"response"` key:

```json
{
  "context": { "id": "..." },
  "response": {
    "weather.strawberry_creek": { "forecast": [...] }
  }
}
```

`tryFetchForecast` was unmarshalling the raw result directly, so `parsed[entity]` was never found. The code silently fell back to the outdoor temp sensor every single time, meaning the thermal battery has never used forecast-based logic since the feature was implemented.

**Changes:**
- `thermal_battery.go`: Add `serviceResponseWrapper` struct and unwrap the `"response"` key in `tryFetchForecast` before parsing entity data
- `thermal_battery_test.go`: Update `makeForecastResponse` to include the real HA API envelope so tests exercise the actual production code path

## Test Plan

- All existing thermal battery tests pass with the new response format in the mock
- `TestThermalBattery_HeatCoolMode_ColdForecast`, `_HotForecast`, and `_MildForecast_SkipsInSkipZone` now exercise the real unwrapping path
- Full test suite: `go test -race ./...` — all pass

🤖 Generated by the AI assistant

### CODE REVIEW

**Comment by NickBorgers** [comment]
## Documentation Review

✅ Approved — pure internal bug fix (JSON envelope unwrap in `loadshedding/thermal_battery.go`); no new plugins, state variables, subscriptions, or concurrency patterns introduced.

File: homeautomation-go/internal/plugins/loadshedding/thermal_battery.go [hunk 1]
```diff
@@ -83,10 +89,19 @@ func (m *Manager) tryFetchForecast(entity string) (float64, float64, bool) {
 		return 0, 0, false
 	}
 
+	// The HA WebSocket API wraps entity data under a "response" key when using
+	// call_service with return_response:true. Unwrap it before parsing entity data.
```
Comment (NickBorgers) [inline homeautomation-go/internal/plugins/loadshedding/thermal_battery.go:87]: Unmarshal error is silently dropped here. Either split the two conditions and log `zap.Error(err)` on the first branch, or at minimum add it to the single log line. Consistent with how the second unmarshal handles it at line 104.

**Review by NickBorgers — COMMENTED** [review]
The combined  branch swallows the unmarshal error — if the raw JSON is malformed, the log says 'missing wrapper' with no error detail. The second unmarshal correctly logs ; this one should too.

**Comment by NickBorgers** [comment]
## Design Review

### Blocking Issues

None.

Scope check: PASS — 18 additions, 3 deletions across 2 files, exactly matching the stated fix.

### Worth Considering

- `serviceResponseWrapper` is used in exactly one place; an inline anonymous struct (`var wrapper struct { Response json.RawMessage \`json:"response"\` }`) would be equally expressive without the package-level declaration — per the project scope discipline guidelines.
- The warning log message `"Weather forecast response missing 'response' wrapper"` fires on both a JSON parse error and a missing key; splitting or adjusting the message would make it easier to distinguish the two failure modes in production logs.

### Conclusion

✅ Approved — correct minimal fix; dropping the issue's suggested silent fallback in favor of a hard return is the right call.

**Comment by NickBorgers** [comment]
## Code Review

### Worth Considering

`thermal_battery.go:95` — the combined `err != nil || wrapper.Response == nil` branch logs `"Weather forecast response missing 'response' wrapper"` but drops `err`, so a malformed-JSON failure is indistinguishable from a missing key in the logs. The second unmarshal on line 104 correctly passes `zap.Error(err)`; this one should too. Not blocking — the fix itself is correct.

### Conclusion

✅ Approved — correct fix for a silent fallback bug; tests now exercise the real HA envelope.

**Comment by NickBorgers** [comment]
## Concurrency Review

✅ Approved — Pure JSON parsing fix with no changes to goroutines, locks, channels, or shared state; all tests pass clean under `-race`.

**Comment by NickBorgers** [comment]
## Test Review

✅ Approved — targeted bug fix correctly unwraps the HA WebSocket API envelope before parsing forecast JSON, with the test helper updated to match the real response shape. All 48 tests pass with `-race`.

**Comment by NickBorgers** [comment]
## 🚦 Merge Decision

**Decision: 🟢 GO**

**Findings addressed:**

- **Code Review "Worth Considering"** (`thermal_battery.go:95` — combined branch drops `err`): **Fixed** — split the `err != nil || wrapper.Response == nil` condition into two separate checks. Malformed JSON now logs `"Weather forecast response JSON malformed"` with `zap.Error(err)`; missing key logs `"Weather forecast response missing 'response' key"` separately. Error detail is no longer silently dropped.

- **Design Review "Worth Considering" #1** (`serviceResponseWrapper` as package-level type used once): **Fixed** — replaced with an inline anonymous struct per project scope discipline ("Don't add helpers or abstractions for one-time operations").

- **Design Review "Worth Considering" #2** (warning message conflates two failure modes): **Fixed** — resolved by the split above; each failure mode now has its own distinct message.

**Spot check:** Diff is 18+/3- lines across 2 files. The core logic (`tryFetchForecast` envelope unwrap + test helper update to match real HA envelope shape) is correct. No unrelated changes. Cross-PR check clean — no conflict with recent merged PRs.

**Applied fixes:** Inlined wrapper struct, split error log branch — committed as `e821d85`, pushed to `ai/issue-1000`. All 34 unit test packages pass (75.1% coverage, above 65% threshold). `gofmt` and `go vet` clean.

Ready for merge to main and production deployment.
